INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (1, 'T_SHIRT', 'MARVEL');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (2, 'CUP', 'MARVEL');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (3, 'COMICS', 'MARVEL');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (4, 'TOYS', 'MARVEL');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (5, 'ACCESSORIES', 'MARVEL');

INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (6, 'T_SHIRT', 'DC');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (7, 'CUP', 'DC');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (8, 'COMICS', 'DC');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (9, 'TOYS', 'DC');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (10, 'ACCESSORIES', 'DC');

INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (11, 'T_SHIRT', 'OTHERS');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (12, 'CUP', 'OTHERS');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (13, 'COMICS', 'OTHERS');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (14, 'TOYS', 'OTHERS');
INSERT INTO PRODUCT(ID, PRODUCT, COMPANY)
VALUES (15, 'ACCESSORIES', 'OTHERS');

INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (1, 1, 10);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (2, 2, 50);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (3, 3, 6);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (4, 4, 7);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (5, 5, 50);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (6, 6, 764);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (7, 7, 33);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (8, 8, 50);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (9, 9, 12);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (10, 10, 33);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (11, 11, 50);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (12, 12, 52);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (13, 13, 58);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (14, 14, 94);
INSERT INTO STOCK(ID, PRODUCT_ID, QUANTITY)
VALUES (15, 15, 11);
